### ISSUE TITLE
Last push inaccurate

### ISSUE THREAD

**Issue by KaKi87** [techgaun/active-forks#32]
Hello,

The "last push" column is always inaccurate while it's the most relevant information we need to find active forks.

Thanks

**Comment by techgaun** [comment]
@KaKi87 ok I'll take a look today and get an update on this here soon

**Comment by techgaun** [comment]
@KaKi87 I ran quick test and it seems to align with data accurately. I will look into more samples but can you also attach the repositor(y|ies) that you were looking into

**Comment by KaKi87** [comment]
For example, I've been looking for an open source MongoDB GUI client for Linux, and I found  [Mongotron](https://github.com/officert/mongotron) but it hasn't been updated since 2016. According to [Active Forks](https://techgaun.github.io/active-forks/index.html#officert/mongotron), [nimatullah's fork](https://github.com/nimatullah/mongotron) has been updated "one month ago", but it actually isn't even up to date to the main repository. I can quote plenty of other examples like this one if I check my browsing history.
Thanks

**Comment by techgaun** [comment]
@kaki87 okay so the code currently uses pushed_at field which is a global representation of the repository i.e. pushes to any branch would result in pushed_at being updated. In the case above with mongotron, there are few branches created via snyk and that's causing pushed_at.

There's a branch api to get latest commit info on a branch and maybe combine that with default branch. But again, for some people, any new push might be important because some forks may be maintaining a separate branch or something. I still need to think what's the best choice here.

**Comment by KaKi87** [comment]
> the code currently uses pushed_at field which is a global representation of the repository i.e. pushes to any branch would result in pushed_at being updated

It seems you're right, and the same thing happened every single time I used Active Forks before, which made me believe that it wasn't working !

> There's a branch api to get latest commit info on a branch and maybe combine that with default branch.

That's exactly what I was thinking about ! However, you don't necessarily have to replace the current updated date but add a new column, right ?

> for some people, any new push might be important

I'd insist on *some* because in most cases, Active Fork's purpose is to find out if there's a more up-to-date alternative version of the software not longer maintained by the original creator, but a non-default branch isn't supposed to be end-user-friendly.

**Comment by KaKi87** [comment]
Hey there, now what about [this one](https://github.com/duhaohao/sinopia) ? I checked all branches and it hasn't been updated for years despite Active Forks says *11 days ago*.

**Comment by mountainash** [comment]
Active Forks: https://techgaun.github.io/active-forks/index.html#cgravolet/scroblr shows deathbeam/scroblr> with a last push of 3 months ago yet there's not any [pushes showing on any of the branches for years](https://github.com/deathbeam/scroblr/branches).

**Comment by KaKi87** [comment]
I'm closing this issue since it has been explained.
