### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by gerchicov-bp** [techgaun/active-forks#35]
I could understand you don't have time/wish to support this repo but what is that?
```
- (CGFloat)width {
    dispatch_async(dispatch_get_main_queue(), ^{
        return self.frame.size.width;
    });
}
```
Function must return its value immediately but you call dispatch_async which of course doesn't work.

**Comment by techgaun** [comment]
hey @gerchicov-bp not sure where you see this bit of code or what you are referring to. that does look like some ios code which should be irrelevant here.
