### ISSUE TITLE
I made a bookmarklet for this

### ISSUE THREAD

**Issue by morrowsend** [techgaun/active-forks#38]
I use this tool periodically but it was always a hassle copying and pasting the repo into this page, so I wrote a bookmarklet for it. Go ahead and throw it on your readme. Just it Ctrl+D to create a new bookmark and paste the javascript below into the URL or "Location" entry.  Any time you're on a github repo you can click the bookmarklet and it'll bring up the activeforks of that repo.

`javascript:var title=document.title;if(title){  thing=title.split(':');var newPage = 'https://techgaun.github.io/active-forks/index.html#'+thing[0];open(newPage ,'targetname')}`

**Comment by techgaun** [comment]
great, thank you. Would you like to create a PR to this repo making note of this on README?

**Comment by morrowsend** [comment]
Yeah, I'll do it now.  Sorry about that.
