### ISSUE TITLE
[Feature request] Direct link to the last push itself

### ISSUE THREAD

**Issue by KaKi87** [techgaun/active-forks#41]
May help figuring #32 out.
Thanks !

**Comment by pktiuk** [comment]
It would be good if it would be added next column containing message of last commit or ID, and whis message would be a link.

**Comment by techgaun** [comment]
up for grab if anyone would like to help

**Comment by KaKi87** [comment]
Since there is actually no such thing as a link to a push, I'm closing this in favor of #54.
