### ISSUE TITLE
better date formatting for last push

### ISSUE THREAD

**Issue by techgaun** [techgaun/active-forks#5]
Right now, its displaying ISO datetime: `2018-10-04T21:00:23Z`. Would be nice to say something like `1 year ago`, `29 days ago` and so on

**Comment by bhagatparwinder** [comment]
I'll do it.

**Comment by MarcosEllys** [comment]
I'll do it

**Comment by MarcosEllys** [comment]
Done

**Comment by bhagatparwinder** [comment]
I'm surprised with the hurry folks are in to get PRs in. Oh well. Just FYI @MarcosEllys you probably don't need to dump moment.js for date formatting of a single element.

@techgaun created a function for timeSince. Either something like that could be created or extended.

**Comment by MarcosEllys** [comment]
I'm so sorry @bhagatparwinder, but, if in the future @techgaun want to make this with N Locales, maybe add moment now, would be a great choose :+1:

**Comment by techgaun** [comment]
closing this as it seems to be done. In the future, maybe we should as a community give the issue out to whoever first responded for taking the issue. Anyway, good discussion. Thanks guys!
