### ISSUE TITLE
TypeError: window.forkTable.clear is not a function. Additional info in console

### ISSUE THREAD

**Issue by sisrfeng** [techgaun/active-forks#50]

**Comment by techgaun** [comment]
@sisrfeng thanks for the issue. Could you please add more information such as what repo you were trying to do this on? On datatable initialization, the `window.forkTable` should normally be created. If its possible, could you please also add screenshot or message that comes up on your browser console?

**Comment by justfra** [comment]
Hello,

I have recently experienced this issue. I have just been using the tool from this page: https://techgaun.github.io/active-forks/index.html

Please find a screenshot below.

![image](https://user-images.githubusercontent.com/396543/114082586-cbe60b00-9862-11eb-8648-b1231d2a7430.png)

**Comment by Barikad** [comment]
Same issue here with this repo: https://github.com/Fmstrat/winapps

**Comment by Barikad** [comment]
> Same issue here with this repo: https://github.com/Fmstrat/winapps

Definitely a client-side issue
My ad blocker was preventing the download of certain JavaScript scripts.

**Comment by techgaun** [comment]
Makes sense. I think for the most part, when we see this error, its likely the js files are not loaded for varieties of reasons such as blocks and in the screenshot from @justfra where it says `ERR_NAME_NOT_RESOLVED`.
