### ISSUE TITLE
demo site seems to be broken

### ISSUE THREAD

**Issue by eladkarako** [techgaun/active-forks#67]
<img width="968" alt="2022-05-03_144034" src="https://user-images.githubusercontent.com/415238/166446378-61ed90b3-bb11-4135-b0ba-0edac2ea5c46.png">

**Comment by dacog** [comment]
FYI @eladkarako : It is working for me at https://techgaun.github.io/active-forks/index.htm

**Comment by eladkarako** [comment]
that's my mistake sorry (kind of),  
I found out a naughty custom uBlock0 rule was blocked `api.github.com/` (instead of `api.github.com/_private/browser/stats`). should probably tag this invalid :|
