### ISSUE TITLE
This is potentially the worst implementation of dark mode ive seen

### ISSUE THREAD

**Issue by ProfessionalSkiddie** [techgaun/active-forks#79]
Inverting the colors looks so ugly, holy

No effort in the dark mode is genuinely crazy it's not even that hard to make...

**Comment by techgaun** [comment]
would you like to make improvements. I would be open to merge the PR if you are able to help

**Comment by ProfessionalSkiddie** [comment]
> would you like to make improvements. I would be open to merge the PR if you are able to help

lmao sorry for being harsh (i was tired)

but sure whenever i can
